#!/usr/bin/python3
import sys
from argparse import ArgumentParser
from signal import signal, SIGINT

from PyDictionary import PyDictionary

INDENT = 2
DICTIONARY = PyDictionary()


write = sys.stdout.write


def die(*_, **__):
    sys.exit()


signal(SIGINT, die)


def write_bold(string):
    write("\033[1m")
    write(string)
    write("\033[0m")


def write_italic(string):
    write("\033[3m")
    write(string)
    write("\033[0m")


def print_meaning(word):
    meaning = DICTIONARY.meaning(word, disable_errors=True)
    if not meaning:
        return
    write_bold(word.capitalize() + ":")
    write("\n")
    for typ, mean in meaning.items():
        write_italic(" " * 2 * INDENT + typ)
        write("\n")
        for i, line in enumerate(mean):
            # format: (indent) i. text
            write(" " * INDENT + str(i + 1) + ". ")
            write(line)
            write("\n")


parser = ArgumentParser()
parser.add_argument("--raw", action="store_true")
parser.add_argument("word", nargs="*")


if __name__ == "__main__":
    args = parser.parse_args()
    words = args.word
    for word in words:
        if args.raw:
            print(DICTIONARY.meaning(word))
        else:
            print_meaning(word)
